# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fowler',
            name='follow_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 2, 8, 59, 54, 948000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fowler',
            name='OpenID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
