# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0005_auto_20160802_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='\u7528\u6237\u53d1\u9001\u4fe1\u606f')),
                ('reply', models.CharField(max_length=200, verbose_name='\u56de\u590d\u4fe1\u606f')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='\u529f\u80fd\u5173\u952e\u5b57')),
                ('explain', models.CharField(max_length=200, verbose_name='\u529f\u80fd\u89e3\u91ca')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='\u7ecf\u5ea6')),
                ('y', models.FloatField(verbose_name='\u7eac\u5ea6')),
                ('label', models.CharField(default='None', max_length=100, verbose_name='\u5730\u7406\u4f4d\u7f6e')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
            ],
        ),
        migrations.RemoveField(
            model_name='fowler',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='fowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Fowler'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='fowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.Fowler'),
        ),
    ]
