# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0006_auto_20160803_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fowler',
            options={'verbose_name_plural': '\u5173\u6ce8\u8005'},
        ),
    ]
